import re
import pandas as pd


LANGUAGE_COLUMN = "language"


def clean_for_excel(value):
    """Remove characters that are not allowed in Excel cells."""
    if isinstance(value, str):
        return re.sub(r"[\x00-\x08\x0B\x0C\x0E-\x1F]", "", value)

    return value


def clean_sheet_name(name):
    """Convert a language name into a valid Excel sheet name."""
    name = str(name).strip()

    for char in r'[]:*?/\\':
        name = name.replace(char, "_")

    return name[:31] or "Unknown"

def remove_duplicated_columns(dataframe):
    # Remove duplicated columns generated by the CSV export
    base_columns = dataframe.columns.str.replace(
        r"\.\d+$",
        "",
        regex=True
    )

    return dataframe.loc[:, ~base_columns.duplicated()]


def process_steam(input_dir, output_dir):
    """
    Convert all Steam review CSV files in input_dir to Excel files.

    Each language is placed in a separate worksheet.
    """

    output_dir.mkdir(parents=True, exist_ok=True)

    csv_files = list(input_dir.glob("*.csv"))

    print(f"Found {len(csv_files)} CSV files.")

    # Loop on all files in the directory
    for csv_file in csv_files:
        print(f"Processing: {csv_file.name}")

        df = pd.read_csv(csv_file)

        df = remove_duplicated_columns(df)

        if LANGUAGE_COLUMN not in df.columns:
            print(
                f"  Skipping: '{LANGUAGE_COLUMN}' column not found."
            )
            continue

        # Remove characters that Excel/OpenPyXL cannot store.
        df = df.map(clean_for_excel)

        output_file = output_dir / f"{csv_file.stem}.xlsx"

        with pd.ExcelWriter(
            output_file,
            engine="openpyxl"
        ) as writer:

            # Create a sheet for every language
            for language, group in df.groupby(
                LANGUAGE_COLUMN,
                dropna=False
            ):
                sheet_name = clean_sheet_name(language)

                group.to_excel(
                    writer,
                    sheet_name=sheet_name,
                    index=False
                )

        print(f"  Created: {output_file}")

    print("Steam processing complete.")